Web/Models/AuthorViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.Models
{
    public class AuthorViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(128, MinimumLength = 2)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(128, MinimumLength = 2)]
        public string LastName { get; set; }

        public IEnumerable<int> ProjectsId { get; set; }


        public string FullName => $"{FirstName} {LastName}";

        public override string ToString() => FullName;
    }
}

Web/ViewModels/AuthorViewModel.cs
using System.Collections.Generic;
using ProjectHubDTO;

namespace Web.ViewModels
{
    public class AuthorViewModel : AuthorDTO
    {
        public List<int> ProjectsId { get; set; } = new();
    }
}

Web/ViewModels/AuthorsListViewModel.cs
using Infrastructure.Data.Entities;
using Web.ViewModels.Pagination;

namespace Web.ViewModels
{
    public class AuthorsListViewModel : BasePaginationViewModel<Author>
    {
    }
}

Web/Controllers/AuthorController.cs
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data.Entities;
using Infrastructure.Data.Entities.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web.ViewModels;

namespace Web.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        private readonly ApplicationContext _db;


        public AuthorController(ApplicationContext db)
        {
            _db = db;
        }


        public async Task<IActionResult> About(int id)
        {
            var author = await _db.Authors
                .Include(a => a.Projects)
                .FirstOrDefaultAsync(a => a.Id == id);

            if (author is null) return NotFound();


            return View(author);
        }


        public async Task<IActionResult> Create()
        {
            var items = await _db.Projects.ToListAsync();

            ViewBag.Projects = new MultiSelectList(items, "Id", "Name");

            return View();
        }

        [HttpPost]
        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Create(AuthorViewModel authorVM)
        {
            if (!ModelState.IsValid) return RedirectToAction();


            var author = new Author()
            {
                FirstName = authorVM.FirstName,
                LastName = authorVM.LastName,
                Projects = await _db.Projects.Where(p => authorVM.ProjectsId.Contains(p.Id)).ToListAsync()
            };

            await _db.Authors.AddAsync(author);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(About), new { author.Id });
        }


        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Edit(int id)
        {
            var author = await _db.Authors
                .Include(a => a.Projects)
                .FirstOrDefaultAsync(a => a.Id == id);

            if (author is null) return NotFound();


            var authorVM = new AuthorViewModel
            {
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName,
                ProjectsId = author.Projects.Select(p => p.Id).ToList()
            };

            var items = await _db.Projects.ToListAsync();

            ViewBag.Projects = new MultiSelectList(items, "Id", "Name", authorVM.ProjectsId);


            return View(authorVM);
        }

        [HttpPost]
        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Edit(int id, AuthorViewModel editedAuthorVM)
        {
            if (!ModelState.IsValid) return RedirectToAction();

            var author = await _db.Authors
                .Include(a => a.Projects)
                .FirstOrDefaultAsync(a => a.Id == id);

            if (author is null) return NotFound();


            author.FirstName = editedAuthorVM.FirstName;
            author.LastName = editedAuthorVM.LastName;
            author.Projects = await _db.Projects.Where(p => editedAuthorVM.ProjectsId.Contains(p.Id)).ToListAsync();

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(About), new { id });
        }


        [HttpGet]
        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await _db.Authors
                .Include(a => a.Projects)
                .FirstOrDefaultAsync(a => a.Id == id);

            if (author is null) return NotFound();


            return View(author);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> DeletePost(int id)
        {
            var author = await _db.Authors
                .FirstOrDefaultAsync(a => a.Id == id);

            if (author is null) return NotFound();


            _db.Authors.Remove(author);
            await _db.SaveChangesAsync();

            return Redirect("~/");
        }
    }
}

Web/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data.Entities;
using Infrastructure.Data.Entities.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Extensions;
using Web.ViewModels;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private const int PageSize = 3;


        private readonly ApplicationContext _db;


        public HomeController(ApplicationContext db)
        {
            _db = db;
        }


        public async Task<IActionResult> Index(int page = 1, string search = "", string order = "")
        {
            ViewData["NameSort"] = string.IsNullOrEmpty(order) ? "name_d" : "";
            ViewData["DateSort"] = order == "date" ? "date_d" : "date";
            ViewData["CurrentSort"] = order;
            ViewData["CurrentSearch"] = search;

            (ViewData["NameSortSymbol"], ViewData["DateSortSymbol"]) = order switch
            {
                "name_d" => ("▼", ""),
                "date" => ("", "▲"),
                "date_d" => ("", "▼"),
                _ => ("▲", "")
            };

            if (page < 1) page = 1;

            IQueryable<Project> query = null;

            if (!string.IsNullOrWhiteSpace(search)) query = _db.Projects.Where(p => p.Name.Contains(search));

            query = query is null
                ? _db.Projects.Include(p => p.Authors)
                : query.Include(p => p.Authors);

            query = order switch
            {
                "date" => query.OrderBy(p => p.CreatedAt),
                "date_d" => query.OrderByDescending(p => p.CreatedAt),
                "name_d" => query.OrderByDescending(p => p.Name),
                _ => query.OrderBy(p => p.Name)
            };

            var pagedProjects = await query.GetPagedAsync(page, PageSize);

            var indexVM = new IndexViewModel()
            {
                Items = pagedProjects,
                PaginationInfo = new(page, PageSize, await query.CountAsync())
            };

            return View(indexVM);
        }

        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> AuthorsList(int page = 1)
        {
            if (page < 1) page = 1;


            var pagedAuthors = await _db.Authors
                .OrderBy(a => a.LastName)
                .GetPagedAsync(page, PageSize);

            var authorsListVM = new AuthorsListViewModel()
            {
                Items = pagedAuthors,
                PaginationInfo = new(page, PageSize, await _db.Authors.CountAsync())
            };

            return View(authorsListVM);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var evm = new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier };

            return View(evm);
        }
    }
}

Web/Controllers/ProjectController.cs
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data.Entities;
using Infrastructure.Data.Entities.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web.ViewModels;

namespace Web.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly ApplicationContext _db;


        public ProjectController(ApplicationContext db)
        {
            _db = db;
        }


        public async Task<IActionResult> About(int id, int page = 1)
        {
            var project = await _db.Projects
                .Include(p => p.Authors)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project is null) return NotFound();

            ViewData["page"] = page;
            return View(project);
        }


        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Create()
        {
            var items = await _db.Authors.ToListAsync();

            ViewBag.Authors = new MultiSelectList(items, "Id", "FullName");

            return View();
        }

        [HttpPost]
        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Create(ProjectViewModel projectVM)
        {
            if (!ModelState.IsValid) return RedirectToAction();


            var project = new Project()
            {
                Name = projectVM.Name,
                CreatedAt = projectVM.CreatedAt,
                Authors = await _db.Authors.Where(p => projectVM.AuthorsId.Contains(p.Id)).ToListAsync()
            };

            await _db.Projects.AddAsync(project);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(About), new { project.Id });
        }


        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Edit(int id)
        {
            var project = await _db.Projects
                .Include(p => p.Authors)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project is null) return NotFound();


            var projectVM = new ProjectViewModel
            {
                Id = project.Id,
                Name = project.Name,
                Description = project.Description,
                CreatedAt = project.CreatedAt,
                AuthorsId = project.Authors.Select(a => a.Id).ToList()
            };

            var items = await _db.Authors.ToListAsync();

            ViewBag.Authors = new MultiSelectList(items, "Id", "FullName", projectVM.AuthorsId);

            return View(projectVM);
        }

        [HttpPost]
        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Edit(int id, ProjectViewModel editedProjectVM)
        {
            if (!ModelState.IsValid) return RedirectToAction();

            var project = await _db.Projects
                .Include(p => p.Authors)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project is null) return NotFound();


            project.Name = editedProjectVM.Name;
            project.Description = editedProjectVM.Description;
            project.CreatedAt = editedProjectVM.CreatedAt;
            project.Authors = await _db.Authors.Where(p => editedProjectVM.AuthorsId.Contains(p.Id)).ToListAsync();

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(About), new { id });
        }


        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            var project = await _db.Projects
                .Include(p => p.Authors)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project is null) return NotFound();


            return View(project);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = Constants.AdminRoleName)]
        public async Task<IActionResult> DeletePost(int id)
        {
            var project = await _db.Projects
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project is null) return NotFound();


            _db.Projects.Remove(project);
            await _db.SaveChangesAsync();


            return RedirectToAction("Index", "Home");
        }
    }
}

Web/Views/Home/Authors.cshtml
@model Infrastructure.Data.Pagination.PagedResult<Author>
@{
    ViewData["Title"] = $"Authors";
}

<h1>Authors</h1>

<div class="container">
    @foreach (var author in Model.Items)
    {
        <div class="container my-4 rounded-lg" style="background-color: #f5f5f5;">
            <div class="h4 d-flex flex-column">
                @Html.ActionLink(author.FullName, "About", "Author", new { id = author.Id })

                <div class="align-self-end">
                    <a class="d-md-none d-inline-block btn-sm btn-outline-warning" asp-controller="Author" asp-action="Edit" asp-route-id="@author.Id" role="button">Edit</a>
                    <a class="d-none d-md-inline-block btn btn-outline-warning" asp-controller="Author" asp-action="Edit" asp-route-id="@author.Id" role="button">Edit</a>
                    <a class="d-md-none d-inline-block btn-sm btn-outline-danger" asp-controller="Author" asp-action="Delete" asp-route-id="@author.Id" role="button">Delete</a>
                    <a class="d-none d-md-inline-block btn btn-outline-danger" asp-controller="Author" asp-action="Delete" asp-route-id="@author.Id" role="button">Delete</a>
                </div>
            </div>
        </div>
    }

    <pagination paged-model="Model.PageViewModel" />
</div>

Web/Views/Home/AuthorsList.cshtml
@model AuthorsListViewModel
@{
    ViewData["Title"] = $"Authors";
}

<h1>Authors</h1>

<div class="container">
    @foreach (var author in Model.Items)
    {
        <div class="container my-4 rounded-lg" style="background-color: #f5f5f5;">
            <div class="h4 d-flex flex-column">
                @Html.ActionLink(author.FullName, "About", "Author", new { id = author.Id })
                
                <div class="align-self-end">
                    <a class="d-md-none d-inline-block btn-sm btn-outline-warning" asp-controller="Author" asp-action="Edit" asp-route-id="@author.Id" role="button">Edit</a>
                    <a class="d-none d-md-inline-block btn btn-outline-warning" asp-controller="Author" asp-action="Edit" asp-route-id="@author.Id" role="button">Edit</a>
                    <a class="d-md-none d-inline-block btn-sm btn-outline-danger" asp-controller="Author" asp-action="Delete" asp-route-id="@author.Id" role="button">Delete</a>
                    <a class="d-none d-md-inline-block btn btn-outline-danger" asp-controller="Author" asp-action="Delete" asp-route-id="@author.Id" role="button">Delete</a>
                </div>
            </div>
        </div>
    }

    <pagination model="Model.PaginationInfo" />
</div>

Web/Views/Home/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Project hub";
    var isAdmin = Context.User.IsInRole(Constants.AdminRoleName);
}

<h1>Project hub</h1>

<div>
    <form method="get">
        <div class="form-group d-flex mb-0">
            <input name="search" class="form-control form-control-sm" id="inputSearch" placeholder="Search" value="@ViewData["CurrentSearch"]">
            <input name="order" value="@ViewData["CurrentSort"]" hidden />
            <button type="submit" class="btn py-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                </svg>
            </button>
        </div>
        <div class="pb-3">
            <a class="px-2" asp-action="Index" asp-route-search="@ViewData["CurrentSearch"]" asp-route-order="@ViewData["NameSort"]">Name @ViewData["NameSortSymbol"]</a>
            <a class="px-2" asp-action="Index" asp-route-search="@ViewData["CurrentSearch"]" asp-route-order="@ViewData["DateSort"]">Created at @ViewData["DateSortSymbol"]</a>
        </div>
    </form>


    @foreach (var project in Model.Items)
    {
        <div class="container my-3 rounded-lg" style="background-color: #f5f5f5;">
            <div class="h4">
                @Html.ActionLink(project.Name, "About", "Project", new { id = project.Id, page = Model.PaginationInfo.CurrentPage })
            </div>
            <div class="w-auto mx-2 mt-2 text-left">
                @foreach (var author in project.Authors)
                {
                    <div class="w-auto small">
                        <a href="~/Author/About/@author.Id">@author.FullName</a>
                    </div>
                }
            </div>
            <div class="m-2 d-flex justify-content-end ">
                <div class="mr-auto">
                    @project.CreatedAt.ToShortDateString()
                </div>
                @if (isAdmin)
                {
                    <div>
                        <a class="text-warning mx-1" asp-controller="Project" asp-action="Edit" asp-route-id="@project.Id" role="button">Edit</a>
                        <a class="text-danger mx-1" asp-controller="Project" asp-action="Delete" asp-route-id="@project.Id" role="button">Delete</a>
                    </div>
                }
            </div>
        </div>
    }

    @if (isAdmin)
    {
        <div class="m-2 d-flex justify-content-end ">
            <a class="btn btn-primary mx-1" asp-controller="Project" asp-action="Create" role="button">New project</a>
            <a class="btn btn-primary mx-1" asp-controller="Author" asp-action="Create" role="button">New author</a>
        </div>
    }

    <pagination model="Model.PaginationInfo"
                page-url-search="@ViewData["CurrentSearch"]" 
                page-url-order="@ViewData["CurrentSort"]"/>

</div>